version: '2'
name: ${DATABASE_DOCKER_CONTAINER_NAME}
services:
  mariadb:
    container_name: ${DATABASE_DOCKER_CONTAINER_NAME}_database
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT}:3306"
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
