---
name: 'Dokku Deployment'

on:
  push:
    branches:
      - feature/dokku-testing

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Backend Deployment
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@balatinac.dev:22/backend'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Frontend Deployment
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@balatinac.dev:22/frontend'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
