name: 'balatinac.dev - Staging - Automated Deployment with PM2'

on:
  push:
    branches:
      - 'develop'

jobs:
  pm2-configuration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Add GitHub to the SSH known hosts file"
        run: |
          mkdir -p -m 0700 /home/runner/.ssh
          curl --silent https://api.github.com/meta | jq --raw-output '"github.com "+.ssh_keys[]' >> /home/runner/.ssh/known_hosts
          chmod 600 /home/runner/.ssh/known_hosts
      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install pm2@latest -g
      - run: pm2 -V
      - run: pm2 ps
      - run: pm2 deploy ecosystem.config.js staging